#!/bin/bash

# Created By: Mr.Exoplanet
# Usage {./recon-web [URL]}
# Enumarates a given website (Will take A Long Time Can Comment Out -A Flag on Nmap And Amass Tool for Quicker Run Time)
# Required Packages Pre Installed {Subfinder}{Assetfinder}{Amass}{Gowitness}
# Set Varaibles & Colours
domain=$1
YELLOW="\033[1;33m"
RESET="\033[0m"

# Create Folders To Store Results
subdomain_path=$domain/subdomains
screenshot_path=$domain/screenshots
scan_path=$domain/scans
if [ ! -d "$domain" ];then
    mkdir $domain
fi
if [ ! -d "$subdomain_path" ];then
    mkdir $subdomain_path
fi
if [ ! -d "$screenshot_path" ];then
    mkdir $screenshot_path
fi
# Run Our Enumarting Tools And Store Them To A Single File

echo -e "${YELLOW} [+] Commencing subfinder |><| ${RESET}"
subfinder -d $domain > $subdomain_path/found.txt

echo -e "${YELLOW} [+] Commencing assetfinder |><| ${RESET}"
assetfinder $domain | grep $domain >> $subdomain_path/found.txt

echo -e "${YELLOW} [+]  Commencing amass |><| ${RESET}"
amass enum -d $domain >> $subdomain_path/found.txt

# Find The Alive Domains Only
echo -e "${YELLOW} [+] Discovering Alive SubDomains |><| ${RESET}"
cat $subdomain_path/found.txt | grep $domain | sort -u | httprobe -prefer-https | grep https | sed 's/https\?:\/\///' | tee -a $subdomain_path/alive.txt

# Taking Screen Shots For A Quick View On Alive Domains
echo -e "${YELLOW} [+] Gathering ScreenShots |><| ${RESET}"
gowitness file -f $subdomain_path/alive.txt -P $screenshot_path/ --no-http

